# Copyright 2025 Ted Lanham
# Licensed under the MIT License
name: Bluetooth WiFi Setup
version: 0.0.1
slug: bluetooth-wifi-setup
description: Configure WiFi via Bluetooth
url: https://github.com/Backroads4Me/ha-addons
arch:
  - aarch64
  - amd64
  - armv7
init: false
host_network: true
host_dbus: true
hassio_api: true
hassio_role: manager
privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - SYS_RAWIO
apparmor: false
startup: application
boot: manual
options:
  bluetooth_timeout: 15
  log_level: info
  device_name: BTBerryWifi
  keep_alive: false
  encryption_enabled: false
schema:
  bluetooth_timeout: int(1,1440)
  log_level: list(debug|info|warning|error)
  device_name: str
  keep_alive: bool
  encryption_enabled: bool
  password: str?
image: ghcr.io/backroads4me/{arch}-bluetooth-wifi-setup-beta
