# Copyright 2025 Ted Lanham
# Licensed under the MIT License
# Add-on configuration file: config.yaml

name: "CAN to MQTT Bridge"
version: "1.0.6"
slug: "can-mqtt-bridge"
description: "Initializes CAN interface and provides a bidirectional CAN-MQTT bridge"
url: "https://github.com/Backroads4Me/ha-addons"
maintainer: "Ted Lanham <tedlanham@gmail.com>"
panel_icon: "mdi:car-connected"
panel_title: "CAN Bridge"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: application
boot: manual
rating: 2
privileged:
  - NET_ADMIN
host_network: true
kernel_modules: true
devices:
  - "/dev/bus/usb"
auth_api: true
apparmor: true
hassio_api: true
hassio_role: default
services:
  - "mqtt:need"
map:
  - "share:rw"
  - "config:ro"
ingress: true
ingress_port: 8099
panel_admin: true
options:
  can_interface: "can0"
  can_bitrate: "250000"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "canbus"
  mqtt_pass: ""
  mqtt_topic_raw: "can/raw"
  mqtt_topic_send: "can/send"
  mqtt_topic_status: "can/status"
  debug_logging: false
  ssl: false
  password: ""
schema:
  can_interface: "str"
  can_bitrate: "list(125000|250000|500000|1000000)"
  mqtt_host: "str"
  mqtt_port: "port"
  mqtt_user: "str"
  mqtt_pass: "password"
  mqtt_topic_raw: "str"
  mqtt_topic_send: "str"
  mqtt_topic_status: "str"
  debug_logging: "bool"
  ssl: "bool"
  password: "password?"
image: ghcr.io/backroads4me/{arch}-can-mqtt-bridge

